# podman compose --file ./compose.yaml up
# --n-gpu-layers 99[or higher as possible (part of layers from "block_count")] --n-cpu-moe 0[or remainder of --n-gpu-layers option] --threads 6 --batch-size 1024 --ubatch-size 2048 --no-op-offload --no-mmap --flash-attn 1

x-project-volumes: &project-volumes
  - project:/project:rw
  - project-ignore:/project/ignore

x-model-volumes: &model-volumes
  - /my/models/path/on/host/machine/incredible-models:/models

x-shell-volumes: &shell-volumes
  - project:/project:rw
  - project-ignore:/project/ignore:ro
  - mcp-shell:/mcp-shell:ro

x-db-postgresql-volumes: &db-postgresql-volumes
  - db-postgresql:/var/lib/postgresql:rw
  - ./postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh

x-dev-tools-volumes: &dev-tools-volumes
  - ~/.ssh/id_rsa_chrome_dev_tools.pub:/root/.ssh/authorized_keys:ro

volumes:
  project:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /my/phoject/path/on/host/machine/awesome-project
  project-ignore:
  db-postgresql:
  mcp-shell:

services:
  codding-server:
    container_name: codding-server
    image: localhost/local/llama.cpp:full-cuda
    ports:
      - "127.0.0.1:9001:9001"
    devices:
      - nvidia.com/gpu=all
    volumes: *model-volumes
    command: ["--server", "-m", "/models/Qwen3-Coder-30B-A3B-Instruct-UD-IQ1_S.gguf", "--port", "9001", "--host", "0.0.0.0", "--jinja", "--metrics", "--ctx-size", "81920"]
    # command: ["--bench", "--verbose", "-m", "/models/Qwen3-Coder-Next-UD-IQ1_S.gguf"]
  sql-server:
    container_name: sql-server
    image: localhost/local/llama.cpp:full-cuda
    depends_on:
      - codding-server
    ports:
      - "127.0.0.1:9002:9002"
    devices:
      - nvidia.com/gpu=all
    volumes: *model-volumes
    command: ["--server", "-m", "/models/Qwen-3-4b-Text_to_SQL-q8_0.gguf", "--metrics", "--port", "9002", "--host", "0.0.0.0", "--jinja", "--metrics"]
  ocr-server:
    container_name: ocr-server
    image: localhost/local/llama.cpp:full-cuda
    depends_on:
      - codding-server
    ports:
      - "127.0.0.1:9003:9003"
    devices:
      - nvidia.com/gpu=all
    volumes: *model-volumes
    command: ["--server", "-m", "/models/GLM-OCR-f16.gguf", "--mmproj", "/models/mmproj-GLM-OCR-Q8_0.gguf", "--no-mmproj-offload", "--port", "9003", "--host", "0.0.0.0", "--jinja", "--metrics"]
  mcp-repomix:
    container_name: mcp-repomix
    image: ghcr.io/yamadashy/repomix
    stdin_open: true
    command: --mcp
    # command: --compress --remove-comments --style markdown --output /project/repomix-output.md /project
    volumes: *project-volumes
  mcp-filesystem-server:
    image: ghcr.io/mark3labs/mcp-filesystem-server:latest
    container_name: mcp-filesystem-server
    stdin_open: true
    command: ["/project"]
    volumes: *project-volumes
  mcp-shell:
    container_name: mcp-shell
    build:
      context: ./mcp/shell-mcp
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes: *shell-volumes
    stdin_open: true
    environment:
      ALLOWED_COMMANDS: ${ALLOWED_COMMANDS}
  mcp-chrome-devtools:
    build:
      dockerfile: Dockerfile
      context: ./mcp/chrome-devtools-mcp
    container_name: mcp-chrome-devtools
    ports:
      - "127.0.0.1:2222:22"
    stdin_open: true
    volumes: *dev-tools-volumes
  db-postgresql:
    container_name: db-postgresql
    build:
      context: ./postgresql/debian/
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - 5432
    volumes: *db-postgresql-volumes
  mcp-crystaldba-postgres:
    container_name: mcp-crystaldba-postgres
    image: crystaldba/postgres-mcp
    depends_on:
      - db-postgresql
    environment:
      DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.containers.internal:${POSTGRES_PORT}/${POSTGRES_DB}
    stdin_open: true
    command: ["--access-mode=unrestricted", "--transport=stdio" ]
