# podman compose --file ./compose.yaml up
# --n-gpu-layers 99[or higher as possible (part of layers from "block_count")] --n-cpu-moe 0[or remainder of --n-gpu-layers option] --threads 6 --batch-size 1024 --ubatch-size 2048 --no-op-offload --no-mmap --flash-attn 1
services:
  codding-server:
    container_name: codding-server
    image: localhost/local/llama.cpp:full-cuda
    ports:
      - "127.0.0.1:9001:9001"
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./models:/models
    command: ["--server", "-m", "/models/Qwen3-Coder-Next-UD-IQ2_XXS.gguf", "--metrics", "--port", "9001", "--host", "0.0.0.0", "--jinja", "--ctx-size", "81920"]
    # command: ["--bench", "--verbose", "-m", "/models/Qwen3-Coder-Next-UD-IQ2_XXS.gguf", "--n-cpu-moe", "18", "--n-gpu-layers", "18", "--threads", "6", "--batch-size", "1024", "--ubatch-size", "2048", "--no-op-offload", "0", "--mmap", "0", "--flash-attn", "1"]
  sql-server:
    container_name: sql-server
    image: localhost/local/llama.cpp:full-cuda
    ports:
      - "127.0.0.1:9002:9002"
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./models:/models
    command: ["--server", "-m", "/models/Qwen-3-4b-Text_to_SQL-F16.gguf", "--metrics", "--port", "9002", "--host", "0.0.0.0", "--jinja"]
  ocr-server:
    container_name: ocr-server
    image: localhost/local/llama.cpp:full-cuda
    ports:
      - "127.0.0.1:9003:9003"
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./models:/models
    command: ["--server", "-m", "/models/Chandra-8.2B-BF16.gguf", "--mmproj", "/models/mmproj-Chandra-BF16.gguf", "--no-mmproj-offload", "--metrics", "--port", "9003", "--host", "0.0.0.0", "--jinja"]
  mcp-filesystem-server:
    image: ghcr.io/mark3labs/mcp-filesystem-server:latest
    container_name: mcp-filesystem-server
    stdin_open: true
    command: ["/project"]
    volumes:
      - project:/project
  mcp-shell:
    container_name: mcp-shell
    build:
      context: ./mcp/shell-mcp
      dockerfile: Dockerfile
    env_file:
      - ./.env.mcp-shell
    stdin_open: true
    volumes:
      - mcp-shell:/mcp-shell:rw
      - project:/project
  mcp-chrome-devtools:
    build:
      dockerfile: Dockerfile
      context: ./mcp/chrome-devtools-mcp
    container_name: mcp-chrome-devtools
    ports:
      - "127.0.0.1:2222:22"
    stdin_open: true
    volumes:
      - ~/.ssh/id_rsa_chrome_dev_tools.pub:/root/.ssh/authorized_keys:ro
  mcp-postgresql:
    container_name: mcp-postgresql
    build:
      context: ./postgresql/debian/
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.postgres
    environment:
      PGDATA: /var/lib/postgresql
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - 5432
    volumes:
      - mcp-postgresql:/var/lib/postgresql:rw
  mcp-crystaldba-postgres:
    container_name: mcp-crystaldba-postgres
    image: crystaldba/postgres-mcp
    depends_on:
      - mcp-postgresql
    environment:
      DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.containers.internal:${POSTGRES_PORT}/${POSTGRES_DB}
    stdin_open: true
    command: ["--access-mode=unrestricted", "--transport=stdio" ]
volumes:
  mcp-shell:
  mcp-postgresql:
  project:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /my/phoject/path/on/host/machine/awesome-project
